# GET
GEt http://localhost:800/datos/
###



# DELETES
DELETE http://localhost:800/datos/2
###



# POST
POST http://localhost:800/datos
Content-Type: application-json "{ "nombre": "Diego","apellido": "Bravo","edad": 20,"cliente": true}"
