# GET
GEt http://localhost:800/datos



# DELETES
DELETE http://localhost:800/datos/8
###




## POST
POST http://localhost:800/datos HTTP/1.1
content-type: application/json

{
	"nombre":"☻" ,
	"apellido": "☺♥",
	"edad": 20,
	"cliente": true
}